/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui;

import Dao.UsuarioDAO;
import Dao.WeightHistDAO;
import Modelo.Cliente;
import Modelo.WeightHist;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;

/**
 *
 * @author conta
 */
public class WeightHistGUI extends javax.swing.JPanel {

    /**
     * Creates new form WeightHistGUI2
     */
    private DefaultTableModel model;
    private UsuarioDAO usuarioDAO;
    private WeightHistDAO weightHistDAO;
    
    
    
 public WeightHistGUI() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        usuarioDAO = new UsuarioDAO();
        weightHistDAO = new WeightHistDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Histórico de Peso");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Peso", "Altura", "IMC", "Data Cadastro"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Consultar Peso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gravar IMC");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String cpf = JOptionPane.showInputDialog("Digite o CPF do cliente:");

    if (cpf != null && !cpf.isEmpty()) {
        // Consultar cliente pelo CPF
        Cliente cliente = usuarioDAO.consultar(cpf);

        if (cliente != null) {
            // Limpar modelo da tabela
            model.setRowCount(0);

            // Consultar histórico de peso do cliente
            List<WeightHist> historico = weightHistDAO.consultarPorCliente(cpf);

            // Adicionar cada registro de peso como uma nova linha na tabela
            for (int i = 0; i < historico.size(); i++) {
                WeightHist registro = historico.get(i);

                // Calcular o IMC
                double alturaMetros = cliente.getAltura() / 100.0; // Converter altura para metros
                double imc = registro.getPeso() / (alturaMetros * alturaMetros);

                model.addRow(new Object[]{
                    cliente.getCpf(), // Deixe em branco para CPF
                    cliente.getNome(), // Deixe em branco para Nome
                    registro.getPeso(),
                    registro.getAltura(),
                    String.format("%.2f", imc), // Formatando o IMC para duas casas decimais
                    registro.getDataCadastro().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "CPF não pode estar vazio.");
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // Obter o número de linhas da tabela
    int rowCount = model.getRowCount();
    
    // Verificar se há linhas na tabela
    if (rowCount > 0) {
        // Abrir janela de diálogo para selecionar arquivo
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showSaveDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();
            
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(selectedFile, true))) {
                for (int i = 0; i < rowCount; i++) {
                    String cpf = (String) model.getValueAt(i, 0);
                    // Corrigindo a conversão do IMC
                    double imc = Double.parseDouble(((String) model.getValueAt(i, 4)).replace(',', '.'));
                    String interpretacao = interpretarIMC(imc);
                    String data = LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                    
                    writer.write("Data: " + data + ", CPF: " + cpf + ", IMC: " + imc + ", Interpretação: " + interpretacao);
                    writer.newLine();
                }
                writer.flush();
                JOptionPane.showMessageDialog(null, "IMC gravado com sucesso!");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao gravar o IMC: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operação de gravação cancelada.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Não há dados para gravar.");
    }
    }

    private String interpretarIMC(double imc) {
        if (imc < 18.5) return "Abaixo do peso";
        else if (imc < 24.9) return "Peso normal";
        else if (imc < 29.9) return "Sobrepeso";
        else return "Obesidade";
    
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
